LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE = native-lib
LOCAL_C_INCLUDES:=$(LOCAL_PATH)/bzip2
LOCAL_CFLAGS = $(L_CFLAGS)
LOCAL_SRC_FILES = bspatch.c
LOCAL_C_INCLUDES = $(INCLUDES)
include $(BUILD_SHARED_LIBRARY)




