/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_bsdiff_ndk_PatchUtils */

#ifndef _Included_com_test_bsdiff_ndk_PatchUtils
#define _Included_com_test_bsdiff_ndk_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_bsdiff_ndk_PatchUtils
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_test_bsdiff_ndk_PatchUtils_bspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
